import {
  Building2,
  Users,
  GitBranch,
  Clock,
  Calendar,
  FileText,
  Percent,
  BellRing,
  Cpu,
  Umbrella,
  CreditCard,
  LayoutDashboard,
  Shield,
  ClipboardList,
  UserCheck,
  Fingerprint,
  DollarSign,
  BarChart2,
  Receipt,
  Landmark,
  PieChart,
  GitCompare,
  CalendarDays,
  AlarmClock,
  Timer,
  Ban,
  CalendarMinus,
  FileClock,
  FileCheck,
  Briefcase,
  Megaphone,
  UserSearch,
  KanbanSquare,
  Sparkles,
  CalendarClock,
  Inbox,
  Filter,
  Hourglass,
  Target,
  AlertTriangle,
  Network,
  UserCog,
  CheckCircle2,
  SlidersHorizontal,
  Layers,
  BadgeCheck,
  UsersRound,
  CalendarCheck,
  CalendarRange,
  Gift,
  CircleMinus,
  UserRound,
  IdCard,
  Wallet,
  Banknote,
  TrendingUp,
  Shuffle,
  Coins,
  Activity,
  Bell,
  KeyRound,
  Minus,
} from "lucide-react";


export interface NavItem {
  key: string;
  label: string;
  path: string;
  icon: React.ElementType;
  permissionKey?: string;
  children?: NavItem[];
}

const navigationConfig: NavItem[] = [
  {
    key: "dashboard",
    label: "Dashboard",
    path: "/dashboard",
    icon: LayoutDashboard,
    // No permission required — everyone sees the dashboard
  },
  {
    key: "organisation",
    label: "Organisation",
    path: "/master",
    icon: Network,
    children: [
      {
        key: "branches",
        label: "Branches",
        path: "/master/branches",
        icon: Building2,
        permissionKey: "MasterData.Branches.View",
      },
      {
        key: "departments",
        label: "Departments",
        path: "/master/departments",
        icon: GitBranch,
        permissionKey: "MasterData.Departments.View",
      },
      {
        key: "designations",
        label: "Designations",
        path: "/master/designations",
        icon: BadgeCheck,
        permissionKey: "MasterData.Designations.View",
      },
      {
        key: "crews",
        label: "Crews",
        path: "/master/crews",
        icon: UsersRound,
        permissionKey: "MasterData.Crews.View",
      },
      {
        key: "groups",
        label: "Groups",
        path: "/master/groups",
        icon: Layers,
        permissionKey: "MasterData.Groups.View",
      },
    ],
  },
  {
    key: "hr",
    label: "HR",
    path: "/hr",
    icon: UserCog,
    children: [
      {
        key: "employees",
        label: "Employees",
        path: "/employees",
        icon: Users,
        permissionKey: "HR.Employee.View",
      },
      {
        key: "leave-requests",
        label: "Leave Requests",
        path: "/transactions/leave-requests",
        icon: UserCheck,
        permissionKey: "Leave.Request.View",
      },
      {
        key: "attendance-logs",
        label: "Attendance Logs",
        path: "/transactions/attendance-logs",
        icon: CalendarCheck,
        permissionKey: "Attendance.Log.View",
      },
    ],
  },
  {
    key: "approvals",
    label: "Approvals",
    path: "/approvals",
    icon: CheckCircle2,
    children: [
      {
        key: "contract-approvals",
        label: "Contract Approvals",
        path: "/contract-approvals",
        icon: FileCheck,
        permissionKey: "HR.EmployeeContract.Approve",
      },
      {
        key: "approve-adjustments",
        label: "Approve Adjustments",
        path: "/transactions/attendance-adjustments",
        icon: Calendar,
        permissionKey: "Attendance.Adjustment.Approve",
      },
      {
        key: "ot-requests",
        label: "Approve Overtime",
        path: "/transactions/ot-requests",
        icon: Timer,
        permissionKey: "Attendance.Ot.Approve",
      },
      {
        key: "loan-approvals",
        label: "Loan Approvals",
        path: "/payroll/loan-approvals",
        icon: Landmark,
        permissionKey: "Payroll.Loan.Approve",
      },
    ],
  },
  {
    key: "recruitment",
    label: "Recruitment",
    path: "/recruitment",
    icon: Briefcase,
    children: [
      {
        key: "requisitions",
        label: "Requisitions",
        path: "/recruitment/requisitions",
        icon: FileCheck,
        permissionKey: "Recruitment.Requisition.View",
      },
      {
        key: "job-postings",
        label: "Job Postings",
        path: "/recruitment/postings",
        icon: Megaphone,
        permissionKey: "Recruitment.Posting.View",
      },
      {
        key: "candidates",
        label: "Candidates",
        path: "/recruitment/candidates",
        icon: UserSearch,
        permissionKey: "Recruitment.Candidate.View",
      },
      {
        key: "pipeline",
        label: "Pipeline",
        path: "/recruitment/pipeline",
        icon: KanbanSquare,
        permissionKey: "Recruitment.Application.View",
      },
      {
        key: "interviews",
        label: "Interviews",
        path: "/recruitment/interviews",
        icon: CalendarClock,
        permissionKey: "Recruitment.Interview.View",
      },
      {
        key: "offers",
        label: "Offers",
        path: "/recruitment/offers",
        icon: Inbox,
        permissionKey: "Recruitment.Offer.View",
      },
      {
        key: "scorecard-templates",
        label: "Scorecard Templates",
        path: "/settings/scorecard-templates",
        icon: ClipboardList,
        permissionKey: "Recruitment.ScorecardTemplate.View",
      },
    ],
  },
  {
    key: "payroll",
    label: "Payroll",
    path: "/payroll",
    icon: CreditCard,
    children: [
      {
        key: "payroll-runs",
        label: "Payroll Runs",
        path: "/transactions/payroll-runs",
        icon: DollarSign,
        permissionKey: "Payroll.PayrollRun.View",
      },
      {
        key: "statutory-rates",
        label: "Statutory Rates",
        path: "/master/statutory-rates",
        icon: Percent,
        permissionKey: "MasterData.StatutoryRates.View",
      },
      {
        key: "tax-config",
        label: "Tax Config",
        path: "/master/tax-config",
        icon: FileText,
        permissionKey: "MasterData.TaxConfig.View",
      },
      {
        key: "loan-types",
        label: "Loan Types",
        path: "/master/loan-types",
        icon: Landmark,
        permissionKey: "Payroll.LoanType.View",
      },
      {
        key: "loans",
        label: "Loans",
        path: "/payroll/loans",
        icon: Minus,
        permissionKey: "Payroll.Loan.View",
      },
    ],
  },
  {
    key: "reports",
    label: "Reports",
    path: "/reports",
    icon: BarChart2,
    children: [
      {
        key: "reports-payroll",
        label: "Payroll",
        path: "#",
        icon: Wallet,
        children: [
          {
            key: "payroll-reports",
            label: "Payroll Summary",
            path: "/transactions/reports",
            icon: DollarSign,
            permissionKey: "Payroll.Reports.View",
          },
          {
            key: "tax-reports",
            label: "Tax (APIT)",
            path: "/reports/tax",
            icon: Receipt,
            permissionKey: "Tax.Reports.View",
          },
          {
            key: "report-bank-transfer",
            label: "Bank Transfer",
            path: "/reports/payroll/bank-transfer",
            icon: Landmark,
            permissionKey: "Reports.BankTransfer.View",
          },
          {
            key: "report-cost-centre",
            label: "Cost Centre",
            path: "/reports/payroll/cost-centre",
            icon: PieChart,
            permissionKey: "Reports.CostCentre.View",
          },
          {
            key: "report-comparison",
            label: "Payroll Comparison",
            path: "/reports/payroll/comparison",
            icon: GitCompare,
            permissionKey: "Reports.Comparison.View",
          },
          {
            key: "report-loan-deduction",
            label: "Loan Deduction",
            path: "/reports/payroll/loan-deduction",
            icon: Banknote,
            permissionKey: "Reports.LoanDeduction.View",
          },
        ],
      },
      {
        key: "reports-hr",
        label: "HR",
        path: "#",
        icon: Users,
        children: [
          {
            key: "report-attendance",
            label: "Attendance Summary",
            path: "/reports/hr/attendance-summary",
            icon: CalendarDays,
            permissionKey: "Reports.Attendance.View",
          },
          {
            key: "report-leave-balance",
            label: "Leave Balance",
            path: "/reports/hr/leave-balance",
            icon: Umbrella,
            permissionKey: "Reports.LeaveBalance.View",
          },
          {
            key: "report-headcount",
            label: "Headcount",
            path: "/reports/hr/headcount",
            icon: UserRound,
            permissionKey: "Reports.Headcount.View",
          },
          {
            key: "report-late-arrivals",
            label: "Late Arrivals",
            path: "/reports/hr/late-arrivals",
            icon: AlarmClock,
            permissionKey: "Reports.LateArrivals.View",
          },
          {
            key: "report-overtime",
            label: "Overtime",
            path: "/reports/hr/overtime",
            icon: Timer,
            permissionKey: "Reports.Overtime.View",
          },
          {
            key: "report-no-pay",
            label: "No-Pay",
            path: "/reports/hr/no-pay",
            icon: Ban,
            permissionKey: "Reports.NoPay.View",
          },
          {
            key: "report-leave-util",
            label: "Leave Utilisation",
            path: "/reports/hr/leave-utilisation",
            icon: CalendarMinus,
            permissionKey: "Reports.LeaveUtil.View",
          },
          {
            key: "report-contract-expiry",
            label: "Contract Expiry",
            path: "/reports/hr/contract-expiry",
            icon: FileClock,
            permissionKey: "Reports.ContractExpiry.View",
          },
        ],
      },
      {
        key: "reports-recruitment",
        label: "Recruitment",
        path: "#",
        icon: TrendingUp,
        children: [
          {
            key: "report-recruitment-funnel",
            label: "Recruitment Funnel",
            path: "/reports/recruitment/funnel",
            icon: Filter,
            permissionKey: "Recruitment.Reports.Funnel.View",
          },
          {
            key: "report-time-to-hire",
            label: "Time to Hire",
            path: "/reports/recruitment/time-to-hire",
            icon: Hourglass,
            permissionKey: "Recruitment.Reports.TimeToHire.View",
          },
          {
            key: "report-source-effectiveness",
            label: "Source Effectiveness",
            path: "/reports/recruitment/source-effectiveness",
            icon: Target,
            permissionKey: "Recruitment.Reports.SourceEffectiveness.View",
          },
          {
            key: "report-requisition-aging",
            label: "Requisition Aging",
            path: "/reports/recruitment/requisition-aging",
            icon: CalendarClock,
            permissionKey: "Recruitment.Reports.RequisitionAging.View",
          },
          {
            key: "report-diversity-snapshot",
            label: "Diversity Snapshot",
            path: "/reports/recruitment/diversity-snapshot",
            icon: Shuffle,
            permissionKey: "Recruitment.Reports.DiversitySnapshot.View",
          },
        ],
      },
    ],
  },
  {
    key: "configuration",
    label: "Configuration",
    path: "/settings",
    icon: SlidersHorizontal,
    children: [
      {
        key: "config-payroll-leave",
        label: "Payroll & Leave Setup",
        path: "#",
        icon: Coins,
        children: [
          {
            key: "shifts",
            label: "Shifts",
            path: "/master/shifts",
            icon: Clock,
            permissionKey: "MasterData.Shifts.View",
          },
          {
            key: "leave-types",
            label: "Leave Types",
            path: "/master/leave-types",
            icon: CalendarRange,
            permissionKey: "MasterData.LeaveTypes.View",
          },
          {
            key: "leave-templates",
            label: "Leave Templates",
            path: "/master/leave-templates",
            icon: FileText,
            permissionKey: "MasterData.LeaveTemplate.View",
          },
          {
            key: "benefit-types",
            label: "Benefit Types",
            path: "/master/benefit-types",
            icon: Gift,
            permissionKey: "MasterData.BenefitTypes.View",
          },
          {
            key: "deduction-types",
            label: "Deduction Types",
            path: "/master/deduction-types",
            icon: CircleMinus,
            permissionKey: "MasterData.DeductionTypes.View",
          },
        ],
      },
      {
        key: "config-attendance-devices",
        label: "Attendance & Devices",
        path: "#",
        icon: Activity,
        children: [
          {
            key: "attendance-policies",
            label: "Attendance Policies",
            path: "/master/attendance-policies",
            icon: Calendar,
            permissionKey: "MasterData.AttendancePolicies.View",
          },
          {
            key: "devices",
            label: "Devices",
            path: "/master/devices",
            icon: Cpu,
            permissionKey: "MasterData.Devices.View",
          },
          {
            key: "biometric-bindings",
            label: "Biometric Bindings",
            path: "/master/biometric-bindings",
            icon: Fingerprint,
            permissionKey: "Biometric.Binding.View",
          },
        ],
      },
      {
        key: "config-calendar-alerts",
        label: "Calendar & Alerts",
        path: "#",
        icon: Bell,
        children: [
          {
            key: "public-holidays",
            label: "Public Holidays",
            path: "/master/public-holidays",
            icon: Umbrella,
            permissionKey: "MasterData.PublicHolidays.View",
          },
          {
            key: "notification-templates",
            label: "Notification Templates",
            path: "/master/notification-templates",
            icon: BellRing,
            permissionKey: "MasterData.NotificationTemplates.View",
          },
          {
            key: "system-alerts",
            label: "System Alerts",
            path: "/settings/system-alerts",
            icon: AlertTriangle,
            permissionKey: "System.Alerts.View",
          },
        ],
      },
      {
        key: "config-banking",
        label: "Banking",
        path: "#",
        icon: Landmark,
        children: [
          {
            key: "bank-branches",
            label: "Bank Branches",
            path: "/master/bank-branches",
            icon: Landmark,
            permissionKey: "MasterData.BankBranches.View",
          },
        ],
      },
      {
        key: "config-ai",
        label: "AI",
        path: "#",
        icon: Sparkles,
        children: [
          {
            key: "ai-features",
            label: "AI Features",
            path: "/settings/ai-features",
            icon: Sparkles,
            permissionKey: "Settings.Company.View",
          },
        ],
      },
      {
        key: "config-company-access",
        label: "Company & Access",
        path: "#",
        icon: KeyRound,
        children: [
          {
            key: "company",
            label: "Company Settings",
            path: "/settings/company",
            icon: Building2,
            permissionKey: "Settings.Company.View",
          },
          {
            key: "users",
            label: "User Accounts",
            path: "/settings/users",
            icon: IdCard,
            permissionKey: "Settings.Users.View",
          },
          {
            key: "roles",
            label: "Roles & Permissions",
            path: "/settings/roles",
            icon: Shield,
            permissionKey: "Settings.Roles.View",
          },
        ],
      },
    ],
  },
];

export function getNavPermissionSections(): {
  label: string;
  keys: string[];
}[] {
  return navigationConfig
    .map((topLevel) => {
      const keys: string[] = [];
      const walk = (item: NavItem) => {
        if (item.permissionKey) keys.push(item.permissionKey);
        item.children?.forEach(walk);
      };
      walk(topLevel);
      return { label: topLevel.label, keys };
    })
    .filter((s) => s.keys.length > 0);
}

export default navigationConfig;

// import {
//   Building2,
//   Users,
//   GitBranch,
//   Clock,
//   Calendar,
//   FileText,
//   Percent,
//   BellRing,
//   Cpu,
//   Umbrella,
//   CreditCard,
//   Minus,
//   Settings,
//   LayoutDashboard,
//   Shield,
//   ClipboardList,
//   UserCheck,
//   Fingerprint,
//   DollarSign,
//   BarChart2,
//   Receipt,
//   Landmark,
//   PieChart,
//   GitCompare,
//   CalendarCheck,
//   AlarmClock,
//   Timer,
//   Ban,
//   CalendarRange,
//   FileClock,
//   FileCheck,
//   Briefcase,
//   Megaphone,
//   UserSearch,
//   KanbanSquare,
//   Sparkles,
//   CalendarClock,
//   Inbox,
//   Filter,
//   Hourglass,
//   Target,
//   AlertTriangle,
// } from "lucide-react";


// export interface NavItem {
//   key: string;
//   label: string;
//   path: string;
//   icon: React.ElementType;
//   permissionKey?: string;
//   children?: NavItem[];
// }

// const navigationConfig: NavItem[] = [
//   {
//     key: "dashboard",
//     label: "Dashboard",
//     path: "/dashboard",
//     icon: LayoutDashboard,
//     // No permission required — everyone sees the dashboard
//   },
//   {
//     key: "master-data",
//     label: "Master Data",
//     path: "/master",
//     icon: Settings,
//     children: [
//       {
//         key: "branches",
//         label: "Branches",
//         path: "/master/branches",
//         icon: Building2,
//         permissionKey: "MasterData.Branches.View",
//       },
//       {
//         key: "departments",
//         label: "Departments",
//         path: "/master/departments",
//         icon: GitBranch,
//         permissionKey: "MasterData.Departments.View",
//       },
//       {
//         key: "designations",
//         label: "Designations",
//         path: "/master/designations",
//         icon: Users,
//         permissionKey: "MasterData.Designations.View",
//       },
//       {
//         key: "shifts",
//         label: "Shifts",
//         path: "/master/shifts",
//         icon: Clock,
//         permissionKey: "MasterData.Shifts.View",
//       },
//       {
//         key: "leave-types",
//         label: "Leave Types",
//         path: "/master/leave-types",
//         icon: Clock,
//         permissionKey: "MasterData.LeaveTypes.View",
//       },
//       {
//         key: "benefit-types",
//         label: "Benefit Types",
//         path: "/master/benefit-types",
//         icon: Clock,
//         permissionKey: "MasterData.BenefitTypes.View",
//       },
//       {
//         key: "leave-templates",
//         label: "Leave Templates",
//         path: "/master/leave-templates",
//         icon: FileText,
//         permissionKey: "MasterData.LeaveTemplate.View",
//       },
//       {
//         key: "statutory-rates",
//         label: "Statutory Rates",
//         path: "/master/statutory-rates",
//         icon: Percent,
//         permissionKey: "MasterData.StatutoryRates.View",
//       },
//       {
//         key: "tax-config",
//         label: "Tax Config",
//         path: "/master/tax-config",
//         icon: FileText,
//         permissionKey: "MasterData.TaxConfig.View",
//       },
//       {
//         key: "attendance-policies",
//         label: "Attendance Policies",
//         path: "/master/attendance-policies",
//         icon: Calendar,
//         permissionKey: "MasterData.AttendancePolicies.View",
//       },
//       {
//         key: "devices",
//         label: "Devices",
//         path: "/master/devices",
//         icon: Cpu,
//         permissionKey: "MasterData.Devices.View",
//       },
//       {
//         key: "biometric-bindings",
//         label: "Biometric Bindings",
//         path: "/master/biometric-bindings",
//         icon: Fingerprint,
//         permissionKey: "Biometric.Binding.View",
//       },
//       {
//         key: "public-holidays",
//         label: "Public Holidays",
//         path: "/master/public-holidays",
//         icon: Umbrella,
//         permissionKey: "MasterData.PublicHolidays.View",
//       },
//       {
//         key: "notification-templates",
//         label: "Notification Templates",
//         path: "/master/notification-templates",
//         icon: BellRing,
//         permissionKey: "MasterData.NotificationTemplates.View",
//       },
//       {
//         key: "crews",
//         label: "Crews",
//         path: "/master/crews",
//         icon: Users,
//         permissionKey: "MasterData.Crews.View",
//       },
//       {
//         key: "groups",
//         label: "Groups",
//         path: "/master/groups",
//         icon: GitBranch,
//         permissionKey: "MasterData.Groups.View",
//       },
//       {
//         key: "bank-branches",
//         label: "Bank Branches",
//         path: "/master/bank-branches",
//         icon: Landmark,
//         permissionKey: "MasterData.BankBranches.View",
//       },
//     ],
//   },
//   {
//     key: "hr",
//     label: "HR",
//     path: "/hr",
//     icon: Users,
//     children: [
//       {
//         key: "employees",
//         label: "Employees",
//         path: "/employees",
//         icon: Users,
//         permissionKey: "HR.Employee.View",
//       },
//       {
//         key: "contract-approvals",
//         label: "Contract Approvals",
//         path: "/contract-approvals",
//         icon: FileCheck,
//         permissionKey: "HR.EmployeeContract.Approve",
//       },
//     ],
//   },
//   {
//     key: "recruitment",
//     label: "Recruitment",
//     path: "/recruitment",
//     icon: Briefcase,
//     children: [
//       {
//         key: "requisitions",
//         label: "Requisitions",
//         path: "/recruitment/requisitions",
//         icon: FileCheck,
//         permissionKey: "Recruitment.Requisition.View",
//       },
//       {
//         key: "job-postings",
//         label: "Job Postings",
//         path: "/recruitment/postings",
//         icon: Megaphone,
//         permissionKey: "Recruitment.Posting.View",
//       },
//       {
//         key: "candidates",
//         label: "Candidates",
//         path: "/recruitment/candidates",
//         icon: UserSearch,
//         permissionKey: "Recruitment.Candidate.View",
//       },
//       {
//         key: "pipeline",
//         label: "Pipeline",
//         path: "/recruitment/pipeline",
//         icon: KanbanSquare,
//         permissionKey: "Recruitment.Application.View",
//       },
//       {
//         key: "interviews",
//         label: "Interviews",
//         path: "/recruitment/interviews",
//         icon: CalendarClock,
//         permissionKey: "Recruitment.Interview.View",
//       },
//       {
//         key: "offers",
//         label: "Offers",
//         path: "/recruitment/offers",
//         icon: Inbox,
//         permissionKey: "Recruitment.Offer.View",
//       },
//     ],
//   },
//   {
//     key: "payroll",
//     label: "Payroll",
//     path: "/payroll",
//     icon: CreditCard,
//     children: [
//       {
//         key: "payroll-runs",
//         label: "Payroll Runs",
//         path: "/transactions/payroll-runs",
//         icon: DollarSign,
//         permissionKey: "Payroll.PayrollRun.View",
//       },
//       // {
//       //   key: "loans",
//       //   label: "Loans",
//       //   path: "/payroll/loans",
//       //   icon: Minus,
//       //   permissionKey: "Payroll.Loan.View",
//       // },
//     ],
//   },
//   {
//     key: "transactions",
//     label: "Transactions",
//     path: "/transactions",
//     icon: ClipboardList,
//     children: [
//       {
//         key: "leave-requests",
//         label: "Leave Requests",
//         path: "/transactions/leave-requests",
//         icon: UserCheck,
//         permissionKey: "Leave.Request.View",
//       },
//       {
//         key: "attendance-logs",
//         label: "Attendance Logs",
//         path: "/transactions/attendance-logs",
//         icon: Clock,
//         permissionKey: "Attendance.Log.View",
//       },
//       {
//         key: "approve-adjustments",
//         label: "Approve Adjustments",
//         path: "/transactions/attendance-adjustments",
//         icon: Calendar,
//         permissionKey: "Attendance.Adjustment.Approve",
//       },
//       {
//         key: "ot-requests",
//         label: "Approve Overtime",
//         path: "/transactions/ot-requests",
//         icon: Timer,
//         permissionKey: "Attendance.Ot.Approve",
//       },
//     ],
//   },
//   {
//     key: "reports",
//     label: "Reports",
//     path: "/reports",
//     icon: BarChart2,
//     children: [
//       {
//         key: "reports-payroll",
//         label: "Payroll",
//         path: "#",
//         icon: DollarSign,
//         children: [
//           {
//             key: "payroll-reports",
//             label: "Payroll Summary",
//             path: "/transactions/reports",
//             icon: DollarSign,
//             permissionKey: "Payroll.Reports.View",
//           },
//           {
//             key: "tax-reports",
//             label: "Tax (APIT)",
//             path: "/reports/tax",
//             icon: Receipt,
//             permissionKey: "Tax.Reports.View",
//           },
//           {
//             key: "report-bank-transfer",
//             label: "Bank Transfer",
//             path: "/reports/payroll/bank-transfer",
//             icon: Landmark,
//             permissionKey: "Reports.BankTransfer.View",
//           },
//           {
//             key: "report-cost-centre",
//             label: "Cost Centre",
//             path: "/reports/payroll/cost-centre",
//             icon: PieChart,
//             permissionKey: "Reports.CostCentre.View",
//           },
//           {
//             key: "report-comparison",
//             label: "Payroll Comparison",
//             path: "/reports/payroll/comparison",
//             icon: GitCompare,
//             permissionKey: "Reports.Comparison.View",
//           },
//           {
//             key: "report-loan-deduction",
//             label: "Loan Deduction",
//             path: "/reports/payroll/loan-deduction",
//             icon: CreditCard,
//             permissionKey: "Reports.LoanDeduction.View",
//           },
//         ],
//       },
//       {
//         key: "reports-hr",
//         label: "HR",
//         path: "#",
//         icon: Users,
//         children: [
//           {
//             key: "report-attendance",
//             label: "Attendance Summary",
//             path: "/reports/hr/attendance-summary",
//             icon: CalendarCheck,
//             permissionKey: "Reports.Attendance.View",
//           },
//           {
//             key: "report-leave-balance",
//             label: "Leave Balance",
//             path: "/reports/hr/leave-balance",
//             icon: Umbrella,
//             permissionKey: "Reports.LeaveBalance.View",
//           },
//           {
//             key: "report-headcount",
//             label: "Headcount",
//             path: "/reports/hr/headcount",
//             icon: Users,
//             permissionKey: "Reports.Headcount.View",
//           },
//           {
//             key: "report-late-arrivals",
//             label: "Late Arrivals",
//             path: "/reports/hr/late-arrivals",
//             icon: AlarmClock,
//             permissionKey: "Reports.LateArrivals.View",
//           },
//           {
//             key: "report-overtime",
//             label: "Overtime",
//             path: "/reports/hr/overtime",
//             icon: Timer,
//             permissionKey: "Reports.Overtime.View",
//           },
//           {
//             key: "report-no-pay",
//             label: "No-Pay",
//             path: "/reports/hr/no-pay",
//             icon: Ban,
//             permissionKey: "Reports.NoPay.View",
//           },
//           {
//             key: "report-leave-util",
//             label: "Leave Utilisation",
//             path: "/reports/hr/leave-utilisation",
//             icon: CalendarRange,
//             permissionKey: "Reports.LeaveUtil.View",
//           },
//           {
//             key: "report-contract-expiry",
//             label: "Contract Expiry",
//             path: "/reports/hr/contract-expiry",
//             icon: FileClock,
//             permissionKey: "Reports.ContractExpiry.View",
//           },
//         ],
//       },
//       {
//         key: "reports-recruitment",
//         label: "Recruitment",
//         path: "#",
//         icon: Briefcase,
//         children: [
//           {
//             key: "report-recruitment-funnel",
//             label: "Recruitment Funnel",
//             path: "/reports/recruitment/funnel",
//             icon: Filter,
//             permissionKey: "Recruitment.Reports.Funnel.View",
//           },
//           {
//             key: "report-time-to-hire",
//             label: "Time to Hire",
//             path: "/reports/recruitment/time-to-hire",
//             icon: Hourglass,
//             permissionKey: "Recruitment.Reports.TimeToHire.View",
//           },
//           {
//             key: "report-source-effectiveness",
//             label: "Source Effectiveness",
//             path: "/reports/recruitment/source-effectiveness",
//             icon: Target,
//             permissionKey: "Recruitment.Reports.SourceEffectiveness.View",
//           },
//           {
//             key: "report-requisition-aging",
//             label: "Requisition Aging",
//             path: "/reports/recruitment/requisition-aging",
//             icon: CalendarClock,
//             permissionKey: "Recruitment.Reports.RequisitionAging.View",
//           },
//           {
//             key: "report-diversity-snapshot",
//             label: "Diversity Snapshot",
//             path: "/reports/recruitment/diversity-snapshot",
//             icon: PieChart,
//             permissionKey: "Recruitment.Reports.DiversitySnapshot.View",
//           },
//         ],
//       },
//     ],
//   },
//   {
//     key: "settings",
//     label: "Settings",
//     path: "/settings",
//     icon: Settings,
//     children: [
//       {
//         key: "ai-features",
//         label: "AI Features",
//         path: "/settings/ai-features",
//         icon: Sparkles,
//         permissionKey: "Settings.Company.View",
//       },
//       {
//         key: "scorecard-templates",
//         label: "Scorecard Templates",
//         path: "/settings/scorecard-templates",
//         icon: ClipboardList,
//         permissionKey: "Recruitment.ScorecardTemplate.View",
//       },
//       {
//         key: "company",
//         label: "Company Settings",
//         path: "/settings/company",
//         icon: Building2,
//         permissionKey: "Settings.Company.View",
//       },
//       {
//         key: "users",
//         label: "User Accounts",
//         path: "/settings/users",
//         icon: Users,
//         permissionKey: "Settings.Users.View",
//       },
//       {
//         key: "roles",
//         label: "Roles & Permissions",
//         path: "/settings/roles",
//         icon: Shield,
//         permissionKey: "Settings.Roles.View",
//       },
//       {
//         key: "system-alerts",
//         label: "System Alerts",
//         path: "/settings/system-alerts",
//         icon: AlertTriangle,
//         permissionKey: "System.Alerts.View",
//       },
//     ],
//   },
// ];

// export default navigationConfig;
// // ← This file needs manual edit — see instructions below
